# Generated by Django 5.1.4 on 2025-01-26 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapplication',
            name='application_document',
            field=models.FileField(blank=True, null=True, upload_to='program_applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
