# Generated by Django 5.1.4 on 2025-01-29 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programapplication',
            name='application_document',
            field=models.FileField(upload_to='program_applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterUniqueTogether(
            name='programapplication',
            unique_together={('student', 'program')},
        ),
    ]
