# Generated by Django 5.1.4 on 2025-01-29 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_programapplication_application_document_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programapplication',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='application_document',
            field=models.FileField(blank=True, null=True, upload_to='program_applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
