# Generated by Django 5.1.4 on 2025-01-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
